server:
  port: 9000
spring:
  application:
    name: VIDEO-API-GATEWAY
  cloud:
    nacos:
      server-addr: 192.168.150.3:8848
    gateway:
      routes:
        - id: sms_router
          uri: lb://VIDEO-API-SMS
          predicates:
            - Path=/api/captchas

        - id: user_router
          uri: lb://VIDEO-API-USERS
          predicates:
            - Path=/api/tokens, /api/token, /api/user, /api/user/videos

        - id: category_router
          uri: lb://VIDEO-API-CATEGORIES
          predicates:
            - Path=/api/categories, /api/categories/**, /api/categories/name

        - id: videos_router
          uri: lb://VIDEO-API-VIDEOS
          predicates:
            - Path=/api/videos/insert

      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
